# MMOMANA - v${project.version}
# an Addon for MMOItems by ASangarin - (Original Plugin by Indyuce)

# DO NOT TOUCH
config-version: 3

# Change default stats here
# Regen unit: <resource> per 'refresh-rate'
default:
    max-mana: 20
    max-stamina: 20
    mana-regeneration: 0.5
    stamina-regeneration: 0.5

# The interval at which regeneration should happen in ticks.
# Default value is 20 ticks which is the same as 1 second.
refresh-rate: 20
# How many % of the players regen value that is ACTUALLY
# regenerated. The formula for how much is regenerated
# per regeneration interval is: (regenerationStat * regenScale)
# For example, if the player has 0.5 mana-regen and the regen-scale
# is set to 0.5 they will only regenerate 0.25 mana each interval.
# This feature exists for smooth scaling of regeneration, while still
# keeping a somewhat "per seconds" or something regen amount.
regen-scale: 1

# The percentage of their max mana/stamina which players
# get as mana/stamina when logging in for the first time
login-ratio:
    mana: 75
    stamina: 75

# Edit here the character used in the resource bars
# in the %mana_<mana/stamina>_bar% placeholder.
resource-bar:
    mana:
        char: █
        length: 20
        colors:
            whole: AQUA
            #You can use HEX colors too:
            #whole: \#223344
            half: DARK_AQUA
            empty: WHITE
    stamina:
        char: █
        length: 20
        colors:
            whole: GREEN
            half: DARK_GREEN
            empty: WHITE

# Crazy Noisy Bizarre Plugin..?